/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_content_delivery_bucket": "someation-20230809135507-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-1",
    "aws_content_delivery_url": "https://d7bfd50lik1ba.cloudfront.net"
};


export default awsmobile;
